### ISSUE TITLE
FEATURE: Generic Network Library

### ISSUE THREAD

**Issue by MaxenceLgt** [DiaboloAB/RType#100]
The goal here is to change the way the Network is used by the game engine by creating a separate network library that defines the most generic possible behavior for clients and servers to meet multiple needs:

- Update the game state
- Allow for easy implementation on any game engine
- Create and manage multiple instances of the same game for matchmaking or game joining

The first expected result is the same as the MVP result for now: players moving across the network and being able to start a game.

**Comment by MaxenceLgt** [comment]
Creation of a Packet Manager. This Packet Manager will allow several things:

- The ability to create and register your own packets derived from APacket using template.
- The ability to create packets deserialized from a buffer.

The purpose of this manager is to provide a simplified & generic usage of the different packets that game developers create.

**Comment by DiaboloAB** [comment]
MVP Done - renewal of issue needed
