### ISSUE TITLE
FEATURE: Server handler & room management

### ISSUE THREAD

**Issue by mlargeot** [DiaboloAB/RType#119]
- Handle migration of the server previously based on the networkhandler of the project into library.
- Add Room/lobby system into the Engine & server manager.

**Comment by MaxenceLgt** [comment]
Main Server handling:
-  connections to server
- room creation (private & matchmaking)
- room joining (pv & mm)
- room leave (pv & mm)
- rom destruction at end of a game

TODO:
- game instance starting & player redirection
- move logger to implement it inside dimension Lib
